### ISSUE TITLE
Shipping Options Minicart: Opção default no seletor de datas

### ISSUE THREAD

**Issue by vmattos** [vtex/front.portal-plugins#12]
Colocar uma opção default no seletor de datas de entrega agendada

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/ML-553)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by vtexcrmgithub** [comment]
Publicação com as Issues: 15,16,17,18,13,12 no ambiente 'Beta'

**Comment by vtexcrmgithub** [comment]
Publicação com as Issues: 19,14,22,23,20,24,15,16,17,18,13,12 no ambiente 'Produção'
