### ISSUE TITLE
Shipping Options Minicart: Enviar attachment quando alterar o valor do seletor

### ISSUE THREAD

**Issue by vmattos** [vtex/front.portal-plugins#17]
- [ ] Enviar attachment quando selecionar alguma opção do seletor
- [ ] Enviar attachment de entrega agendada somente quando selecionar o horário ou data
- [ ] Remover o botão de confirmar opção

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/ML-558)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by vtexcrmgithub** [comment]
Publicação com as Issues: 15,16,17,18,13,12 no ambiente 'Beta'

**Comment by vtexcrmgithub** [comment]
Publicação com as Issues: 19,14,22,23,20,24,15,16,17,18,13,12 no ambiente 'Produção'
