### ISSUE TITLE
Shipping Options Minicart: Exibir próximas datas de entrega de cada sla

### ISSUE THREAD

**Issue by vmattos** [vtex/front.portal-plugins#21]

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/ML-571)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by vmattos** [comment]
Same issue: #19
