### ISSUE TITLE
Shipping Options Minicart: Remover seletor de delivery windows ao selecionar "Escolha uma data"

### ISSUE THREAD

**Issue by vmattos** [vtex/front.portal-plugins#24]

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/PI-628)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by vtexcrmgithub** [comment]
Publicação com as Issues: 19,14,22,23,20,24 no ambiente 'Beta'

**Comment by vtexcrmgithub** [comment]
Publicação com as Issues: 19,14,22,23,20,24,15,16,17,18,13,12 no ambiente 'Produção'
