### ISSUE TITLE
Shipping Options Minicart: Alterar formato da data

### ISSUE THREAD

**Issue by vmattos** [vtex/front.portal-plugins#25]
Deve ser: 
Quarta-feira, 04/02/2015

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/ML-611)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)
